name: Generate Readme

on:
  push:
    branches:
      - master

jobs:
  generate-readme:
    run: "jupyter nbconvert --execute generate_readme.ipynb --inplace"
    run: "jupyter nbconvert --clear-output --inplace generate_readme.ipynb"
